# Generated by Django 6.0.7 on 2026-07-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carro', models.CharField(max_length=100)),
                ('sensor', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('hora', models.DateTimeField()),
            ],
        ),
    ]
